### ISSUE TITLE
Project Abandoned.

### ISSUE THREAD

**Issue by Ni3zam** [dialtoneuk/SyscrackLegacy#8]
Im sorry to say,but this project already abandoned due to the main developer abandon this project.
And now all developer for SysCrack already quit to develop this project.

**Comment by dialtoneuk** [comment]
Project is still alive!

New update will be pushed soon with major fixes!

![license](https://user-images.githubusercontent.com/5281091/35164528-87fb404a-fd42-11e7-98d4-19f7a87bd865.PNG)
![research](https://user-images.githubusercontent.com/5281091/35164529-8810f778-fd42-11e7-89bf-1344181229ab.PNG)
